print('Ceci est mon projet')
print('juste pour tester')
print('Je fais des modifications depuis la branche MS2D')
print('La validation se fera après')
print('Derniere modification sur le code')
print('Ndiawar WADE : Ma modification')
